---
title: 'Gerrymandering: Session 4 Data Analysis'
author: "An, Anderson, and Deck"
date: "2/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
df_clean <- read.csv("Simp_Data_04.csv")
df1 <- subset(df_clean, Subject == 1)
df2 <- subset(df_clean, Subject == 2)
df3 <- subset(df_clean, Subject == 3)
df4 <- subset(df_clean, Subject == 4)
df5 <- subset(df_clean, Subject == 5)
df6 <- subset(df_clean, Subject == 6)
df7 <- subset(df_clean, Subject == 7)
df8 <- subset(df_clean, Subject == 8)
```


```{r}
library(ggplot2)
Fig1 <- ggplot(df1, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig2 <- ggplot(df2, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig3 <- ggplot(df3, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig4 <- ggplot(df4, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig5 <- ggplot(df5, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig6 <- ggplot(df6, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig7 <- ggplot(df7, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
Fig8 <- ggplot(df8, aes(Period, Effort, color = District)) +
  geom_line(size = 1.5) +
  facet_wrap(~Map) + 
  theme(text = element_text(size=35),
        legend.key.height= unit(2, 'cm'),
        legend.key.width= unit(4, 'cm'),
        legend.title = element_text(size=20),
        legend.text = element_text(size=15))
```


## Subject 1

```{r fig.height=10, fig.width=15}
print(Fig1)
```


## Subject 2

```{r fig.height=10, fig.width=15}
print(Fig2)
```


## Subject 3

```{r fig.height=10, fig.width=15}
print(Fig3)
```


## Subject 4

```{r fig.height=10, fig.width=15}
print(Fig4)
```


## Subject 5

```{r fig.height=10, fig.width=15}
print(Fig5)
```


## Subject 6

```{r fig.height=10, fig.width=15}
print(Fig6)
```


## Subject 7

```{r fig.height=10, fig.width=15}
print(Fig7)
```


## Subject 8

```{r fig.height=10, fig.width=15}
print(Fig8)
```

## Map Choice Over Time Across Subjects

```{r}
df_clean$Map_Choice <- as.character(as.numeric(df_clean$Map_Choice))

ggplot(df_clean, aes(Period, Map_Choice, color = Map_Choice)) +
  geom_point() +
  facet_wrap(~Subject) + ylab("Map Choice") + scale_colour_discrete("Map Choice")
```

